# Based on https://github.com/morhetz/gruvbox by morhetz <morhetz@gmail.com>

cursor                  #8ba37e
cursor_text_color       background

url_color               #67808a

visual_bell_color       #8ba37e
bell_border_color       #8ba37e

active_border_color     #c6685d
inactive_border_color   #665c54

foreground              #e5dec9
background              #242120
selection_foreground    #e5dec9
selection_background    #8ba37e

active_tab_foreground   #e5dec9
active_tab_background   #8ba37e
inactive_tab_foreground #e5dec9
inactive_tab_background #665C54

# black  (bg3/bg4)
color0                  #242120
color8                  #36312f

# red
color1                  #c6685d
color9                  #db8177

#: green
color2                  #8ba37e
color10                 #9cb793

# yellow
color3                  #cb9168
color11                 #e2aa82

# blue
color4                  #67808a
color12                 #809ba6

# magenta
color5                  #a27886
color13                 #bc919f

# cyan
color6                  #769f93
color14                 #92b9ad

# white (fg4/fg3)
color7                  #e5dec9
color15                 #f4eedc
